packages:
  - "apps/*"
  - "packages/*"
autoInstallPeers: true
strictPeerDependencies: false
nodeLinker: isolated
packageImportMethod: auto
trustLockfile: true
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
